
import { ChecklistItem } from './types';

export const initialItems: ChecklistItem[] = [
  { id: "1", text: "Lit bébé", checked: false, category: "Chambre" },
  { id: "2", text: "Matelas pour lit bébé", checked: false, category: "Chambre" },
  { id: "3", text: "Draps-housses (au moins 3)", checked: false, category: "Chambre" },
  { id: "4", text: "Couvertures légères", checked: false, category: "Chambre" },
  { id: "5", text: "Mobile musical", checked: false, category: "Chambre" },
  { id: "6", text: "Moniteur bébé", checked: false, category: "Chambre" },
  { id: "7", text: "Veilleuse", checked: false, category: "Chambre" },
  { id: "8", text: "Gigoteuses (2-3)", checked: false, category: "Vêtements" },
  { id: "9", text: "Bodies (8-10)", checked: false, category: "Vêtements" },
  { id: "10", text: "Pyjamas (5-6)", checked: false, category: "Vêtements" },
  { id: "11", text: "Chaussettes/chaussons (4-5 paires)", checked: false, category: "Vêtements" },
  { id: "12", text: "Bonnets (2)", checked: false, category: "Vêtements" },
  { id: "13", text: "Brassières en laine (2)", checked: false, category: "Vêtements" },
  { id: "14", text: "Bavoirs (6-8)", checked: false, category: "Vêtements" },
  { id: "15", text: "Tenues de sortie (4-5)", checked: false, category: "Vêtements" },
  { id: "16", text: "Table à langer", checked: false, category: "Hygiène" },
  { id: "17", text: "Matelas à langer", checked: false, category: "Hygiène" },
  { id: "18", text: "Baignoire pour bébé", checked: false, category: "Hygiène" },
  { id: "19", text: "Transat de bain", checked: false, category: "Hygiène" },
  { id: "20", text: "Thermomètre de bain", checked: false, category: "Hygiène" },
  { id: "21", text: "Couches nouveau-né", checked: false, category: "Hygiène" },
  { id: "22", text: "Lingettes ou coton", checked: false, category: "Hygiène" },
  { id: "23", text: "Liniment ou eau nettoyante", checked: false, category: "Hygiène" },
  { id: "24", text: "Sérum physiologique", checked: false, category: "Hygiène" },
  { id: "25", text: "Crème pour le change", checked: false, category: "Hygiène" },
  { id: "26", text: "Thermomètre médical", checked: false, category: "Hygiène" },
  { id: "27", text: "Ciseaux à ongles à bouts ronds", checked: false, category: "Hygiène" },
  { id: "28", text: "Poussette", checked: false, category: "Déplacements" },
  { id: "29", text: "Siège auto", checked: false, category: "Déplacements" },
  { id: "30", text: "Porte-bébé ou écharpe de portage", checked: false, category: "Déplacements" },
  { id: "31", text: "Sac à langer", checked: false, category: "Déplacements" },
  { id: "32", text: "Biberons (4-6)", checked: false, category: "Alimentation" },
  { id: "33", text: "Tétines adaptées à l'âge", checked: false, category: "Alimentation" },
  { id: "34", text: "Goupillon pour biberons", checked: false, category: "Alimentation" },
  { id: "35", text: "Chauffe-biberon", checked: false, category: "Alimentation" },
  { id: "36", text: "Stérilisateur", checked: false, category: "Alimentation" },
  { id: "37", text: "Lait infantile", checked: false, category: "Alimentation" },
  { id: "38", text: "Coussin d'allaitement", checked: false, category: "Alimentation" },
  { id: "39", text: "Tire-lait (si allaitement)", checked: false, category: "Alimentation" },
  { id: "40", text: "Doudou", checked: false, category: "Éveil" },
  { id: "41", text: "Tapis d'éveil", checked: false, category: "Éveil" },
  { id: "42", text: "Jouets de préhension", checked: false, category: "Éveil" },
  { id: "43", text: "Livre en tissu", checked: false, category: "Éveil" },
];
