// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxynugnbikiwbsqdgewx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4eW51Z25iaWtpd2JzcWRnZXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTA0MTIsImV4cCI6MjA2MDM4NjQxMn0.NBN7Fvdai5D5jCMnPyNKHrENNj1eDdcaajsPlWaME_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);